export const ADD_TO_CART = "ADD_TO_CART"
export const GET_ART = "GET_ART"
export const UPDATE_CART = "UPDATE_CART"
export const CHECKOUT = "CHECKOUT"
export const UPLOAD_GALLERY = "UPLOAD_GALLERY"
export const PURCHASED = "PURCHASED"
export const DELETE_CART = "DELETE_CART"

export const LOGIN = "LOGIN"
export const REGISTER = "REGISTER"
export const LOGOUT = "LOGOUT"
export const USER_LOADED = "USER_LOADED"
export const AUTH_ERROR = "AUTH_ERROR"

export const SET_ALERT = "SET_ALERT"
export const REMOVE_ALERT = "REMOVE_ALERT"
export const CLEAR_PURCHASE = "CLEAR_PURCHASE"
