export const ADD_TO_CART = "ADD_TO_CART"
export const GET_ART = "GET_ART"
export const RELOAD_CART = "RELOAD_CART"
export const CHECKOUT = "CHECKOUT"
export const GET_STOCK = "GET_STOCK"
export const UPDATE_STOCK = "UPDATE_STOCK"